WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/FruitModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class FruitModel
    {
        public int fruitidx { get; set; }
        public string name { get; set; }
    }
}

WebApp/Models/GoodsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class GoodsModel
    {
        public int goodsidx { get; set; }
        public int fruitidx { get; set; }
        public int price { get; set; }
    }
}

WebApp/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class OrderModel
    {
        public int orderidx { get; set; }
        public int goodsidx { get; set; }
        public DateTime orderdate { get; set; }
    }
}

WebApp/Models/SampleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class SampleViewModel
    {
        public string Name { get; set; }
        public int ModifyIdx { get; set; }
        public List<FruitModel> Fruits { get; set; }
        
    }
}

WebApp/Models/StoreModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class StoreModel
    {
        public int storeidx { get; set; }

        public string storename { get; set; }
        public string delegatename { get; set; }
    }
}

WebApp/Models/WebAppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class WebAppDbContext : DbContext
    {
        public WebAppDbContext(DbContextOptions<WebAppDbContext> options) 
            : base(options)
        {

        }

        public DbSet<FruitModel> Fruit { get; set; }
        public DbSet<GoodsModel> Goods { get; set; }
        public DbSet<OrderModel> Order { get; set; }
        public DbSet<StoreModel> Store { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FruitModel>(entity =>
            {
                entity.HasKey(e => e.fruitidx)
                    .HasName("PRIMARY");

                entity.ToTable("fruit");

                entity.Property(e => e.fruitidx)
                    .HasColumnName("fruitidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.name)
                    .HasColumnType("varchar(100)")
                    .HasCharSet("utf8")
                    .HasCollation("utf8_bin");

            });

            modelBuilder.Entity<GoodsModel>(entity =>
            {
                entity.HasKey(e => e.goodsidx)
                    .HasName("PRIMARY");

                entity.ToTable("goods");

                entity.Property(e => e.goodsidx)
                    .HasColumnName("goodsidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.fruitidx)
                    .HasColumnName("fruitidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.price)
                   .HasColumnName("price")
                   .HasColumnType("int(11)");

            });

            modelBuilder.Entity<OrderModel>(entity =>
            {
                entity.HasKey(e => e.orderidx)
                    .HasName("PRIMARY");

                entity.ToTable("order");

                entity.Property(e => e.orderidx)
                    .HasColumnName("orderidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.goodsidx)
                    .HasColumnName("goodsidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.orderdate).HasColumnType("datetime");

            });

            modelBuilder.Entity<StoreModel>(entity =>
            {
                entity.HasKey(e => e.storeidx)
                    .HasName("PRIMARY");

                entity.ToTable("store");

                entity.Property(e => e.storeidx)
                    .HasColumnName("storeidx")
                    .HasColumnType("int(11)");

                entity.Property(e => e.storename)
                    .HasColumnType("varchar(100)")
                    .HasCharSet("utf8")
                    .HasCollation("utf8_bin");

                entity.Property(e => e.delegatename)
                    .HasColumnType("varchar(50)")
                    .HasCharSet("utf8")
                    .HasCollation("utf8_bin");

            });
        }

    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/SampleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SampleController : Controller
    {
        private readonly WebAppDbContext db;

        public SampleController(WebAppDbContext dbContext)
        {
            db = dbContext;
        }


        [HttpGet]
        public IActionResult Order()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Fruit(int? idx)
        {
            SampleViewModel vm = new SampleViewModel();
            vm.Fruits = db.Fruit.ToList();

            if (idx == null)
            {
                vm.Name = string.Empty;
                vm.ModifyIdx = 0;
            }
            else
            {
                vm.Name = db.Fruit.Find(idx).name;
                vm.ModifyIdx = (int)idx;
            }

            return View(vm);
        }

        [HttpPost]
        public IActionResult Fruit(SampleViewModel vm)
        {
            if (!string.IsNullOrEmpty(vm.Name))
            {
                if(vm.ModifyIdx == 0)
                {
                    FruitModel fruit = new FruitModel();
                    fruit.name = vm.Name;
                    db.Fruit.Add(fruit);
                    db.SaveChanges();
                }
                else
                {
                    FruitModel fruit = db.Fruit.Find(vm.ModifyIdx);
                    fruit.name = vm.Name;
                    db.Fruit.Update(fruit);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Fruit");
        }

        [HttpGet]
        public IActionResult DeleteFruit(int idx)
        {
            var fruit = db.Fruit.Find(idx);
            db.Fruit.Remove(fruit);
            db.SaveChanges();

            return RedirectToAction("Fruit");
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Sample/Fruit.cshtml
@using WebApp.Models;

@{
    Layout = "_Layout";
    @model SampleViewModel
}

 

<div>
    <h2>Fruit</h2>
    @using (Html.BeginForm("Fruit", "Sample", null, FormMethod.Post))
    {
        <label>Name :</label>
        @Html.HiddenFor(m => m.ModifyIdx)
        @Html.TextBoxFor(m => m.Name)
        @if (Model.ModifyIdx == 0) {<button type="submit">Add</button>}
        else {<button type="submit">Modify</button> }
    }
    <div style="margin-bottom: 60px;"></div>
    <table style="border: 1px solid black; width: 50%;">
        <thead>
            <tr style="border: 1px solid black;">
                <td style="border: 1px solid black;">ID</td>
                <td style="border: 1px solid black;">Name</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var fruit in Model.Fruits)
            {
                <tr style="border: 1px solid black;">
                    <td style="border: 1px solid black;">@fruit.fruitidx</td>
                    <td style="border: 1px solid black;">@fruit.name</td>
                    <td>
                        <a href="/sample/deletefruit?idx=@fruit.fruitidx" style="background-color: red; cursor: pointer; color: white; margin: 5px; border: 1px solid white;">삭제</a>
                        <a href="/sample/fruit?idx=@fruit.fruitidx" style="background-color: turquoise; cursor: pointer; color: white; margin: 5px; border: 1px solid white;">수정</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebApp/Views/Sample/Order.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>